# Generated by Django 3.0 on 2021-02-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='important',
        ),
    ]
