# Generated by Django 3.0 on 2021-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
